const BASE_URL = process.env.EXPO_PUBLIC_API_URL;
//const BASE_URL = "http://127.0.0.1:8080"
export const MEMBER_URL = `${BASE_URL}/members`;
export const LETTERS_HOTEL_URL = `${BASE_URL}/letters/hotel`;
export const LETTERS_URL = `${BASE_URL}/letters`;
export const AUTH_URL = `${BASE_URL}/auth`;
export const HOTEL_URL = `${BASE_URL}/hotel`;
export const REPLIES_URL = `${BASE_URL}/replies`;
export const VILLAGE_URL = `${BASE_URL}/villages`;